name: Publish NPM package + Docs
on:
  release:
    types: [created]
jobs:
  publish_discord:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
        
      - name: Publish on discord
        run: node .github/discord.js channel="828881761072709639" body="${{ github.event.release.body }}" tag="${{ github.event.release.tag_name }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.BOT_TOKEN }}
